title: 'IGH Labeling Tool'
author: 'Tung'

# drawing configuration for QPen - only show on drawing
# - color {tuple}: RGBA label color
# - thickness {int}: QPen thickness
# - style: QPen style
draw:
  color: [255, 0, 0]
  thickness: 5
  style: Qt.SolidLine

# select configuration for QPen - only show when selected
# - color {tuple}: RGBA label color
# - thickness {int}: QPen thickness
# - style: QPen style
select:
  color: [255, 0, 255]
  thickness: 5
  style: Qt.SolidLine

# label configuration for cv2 - show drawn recorded
# - color {tuple}: RGB label color
# - thickness {int}: label thickness
label:
  color: [0, 0, 255]
  thickness: 10

# limit_nlabel: limited number of labels per frame, no limit if value is None
limit_nlabel: 10000000


classes:
 
#  thucquan.pt: 
  - Viem_thuc_quan 
  - Ung_thu_thuc_quan
#  daday.pt: 
  - Viem_da_day_HP_am 
  - Viem_da_day_HP_duong 
  - Ung_thu_da_day
#  htt.pt: 
  - Loet_HTT